### ISSUE TITLE
Add description of program to README.md #7

### ISSUE THREAD

**Issue by omarmohamud23** [omarmohamud23/readinglist#1]
Add a short description of the program and it's features to README.md

**Comment by omarmohamud23** [comment]
@johnnyvuanly I added a description to ReadMe.md.  Please take a look at it.

**Comment by johnnyvuanly** [comment]
@omarmohamud23 I saw the description you added. Looks good, now I will close the issue.

**Comment by claraj** [comment]
which PR is this in?
